name: test
on:
- pull_request
jobs:
  focal:
    container:
      image: swift:5.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test
  test-exports:
    name: Test exports
    runs-on: ubuntu-latest
    steps:
      - name: Check out Vapor
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: swift build -Xswiftc -DBUILDING_DOCC